### PR TITLE
Added Splash Screen

### PR DESCRIPTION
**Pull request by shruti512**

### CODE REVIEW

**Comment by shruti512** [comment]
I have added a splash screen. You can change the UI as per your wish.

**Comment by mohandas-pai** [comment]
Looks good. Thanks

**Comment by shruti512** [comment]
Hey, Can you add "hacktoberfest" topic in about section of this repo so the PRs can be eligible. They have changed some rules.

**Comment by mohandas-pai** [comment]
I added, is it fine now?

**Comment by shruti512** [comment]
Can you add the "hacktoberfest-accepted" label to this merge if possible?

**Comment by shruti512** [comment]
Done. Thanks!

**Pull request merged**
